spring:
  application:
    name: server-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tyrival/SpringCloudConfig/
          searchPaths: repo
          username:
          password:
    bus:
      enabled: true
      trace:
        enabled: true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin

server:
  port: 9000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh