# 在依赖Redis的模块的application中增加如下配置
spring:
  cache:
    type: redis
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123
    maxAttempts: 5
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-wait: 5000
        max-idle: 50
        min-idle: 0