spring:
  cache:
    type: redis
  redis:
    password:
    maxAttempts: 5
    timeout: 2000ms
    jedis:
      pool:
        max-active: 8
        max-wait: 5000ms
        max-idle: 50
        min-idle: 0
    cluster:
      nodes:
        - 127.0.0.1:6379